import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, LegalSection } from "@/components/legal/legal-page";
import { getSetting } from "@/lib/server/settings";

export const metadata: Metadata = {
  title: "Privacy Policy — SureCash Mining",
};

const UPDATED = "August 2026";

export default async function PrivacyPolicyPage() {
  const companyRcNumber = await getSetting("company_rc_number", "");
  const companyOfficeAddress = await getSetting("company_office_address", "NO. 23, UDOEDEHE STREET, UYO.");

  return (
    <LegalPage
      title="Privacy Policy"
      updated={UPDATED}
      intro="This Privacy Policy explains what information SureCash Mining collects, how we use it, and the choices you have. By creating an account or using the platform, you agree to the practices described here."
    >
      <LegalSection title="1. Information we collect">
        <p>We collect information you provide directly and information generated by your use of the platform:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Account details — full name, email address, phone number, and password (stored as a salted hash, never in plain text).</li>
          <li>Identity verification (KYC) — government-issued ID and any documents you submit when we verify your identity.</li>
          <li>Payout details — bank account numbers, account names, and USDT wallet addresses you add for withdrawals.</li>
          <li>Voice recordings you submit for Voice AI Tasks, used to verify authenticity and pay out rewards.</li>
          <li>Activity data — mining claims, task completions, referrals, spins, deposits, withdrawals, and login history.</li>
          <li>Device and session data — IP address, device type, and browser/app information, used for security (e.g. login alerts, fraud detection).</li>
        </ul>
      </LegalSection>

      <LegalSection title="2. How we use your information">
        <ul className="list-disc space-y-1 pl-5">
          <li>To create and secure your account, and authenticate you when you log in.</li>
          <li>To operate the earning features — voice tasks, mining, the Task Center, referrals, Mining Plans, and the Lucky Spin.</li>
          <li>To process deposits and withdrawals through our payment partners.</li>
          <li>To verify your identity (KYC) where required, and to detect and prevent fraud, duplicate accounts, and abuse.</li>
          <li>To send transactional notifications — wallet activity, login alerts, withdrawal status — by email, SMS, WhatsApp, or push notification.</li>
          <li>To respond to support requests and enforce our Terms and Conditions.</li>
        </ul>
      </LegalSection>

      <LegalSection title="3. Who we share information with">
        <p>We do not sell your personal information. We share it only where necessary to operate the platform:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Payment and payout processors (such as Paystack, Flutterwave, Monnify, and Korapay) to complete deposits and withdrawals.</li>
          <li>Email, SMS, and WhatsApp providers to deliver account and transaction notifications.</li>
          <li>Law enforcement or regulators, where required by Nigerian law or to investigate fraud.</li>
          <li>Service providers who help us run the platform (e.g. hosting, AI validation of voice recordings), under obligations to protect your data.</li>
        </ul>
      </LegalSection>

      <LegalSection title="4. Data security">
        <p>
          Passwords are hashed, not stored in plain text. Sensitive actions (login, withdrawals, payout-detail changes) can trigger
          email/SMS alerts and, where enabled, additional verification. No system is perfectly secure, but we take reasonable
          technical and organizational measures to protect your data from unauthorized access, loss, or misuse.
        </p>
      </LegalSection>

      <LegalSection title="5. Data retention">
        <p>
          We retain account and transaction data for as long as your account is active and for a reasonable period afterward, to
          meet legal, tax, and fraud-prevention obligations. KYC documents are retained only as long as necessary for
          verification and compliance purposes.
        </p>
      </LegalSection>

      <LegalSection title="6. Your rights">
        <p>
          You can review and update most of your account details from your Profile. You may request a copy of the personal data
          we hold about you, or request that we delete your account, by contacting Support — subject to our legal obligation to
          retain certain financial records.
        </p>
      </LegalSection>

      <LegalSection title="7. Children's privacy">
        <p>SureCash Mining is not intended for anyone under 18. We do not knowingly collect data from minors.</p>
      </LegalSection>

      <LegalSection title="8. Changes to this policy">
        <p>
          We may update this Privacy Policy from time to time. Material changes will be reflected by an updated &quot;Last
          updated&quot; date above. Continued use of the platform after a change means you accept the revised policy.
        </p>
      </LegalSection>

      <LegalSection title="9. Contact us">
        <p>
          Questions about this policy or your data can be sent through the{" "}
          <Link href="/support" className="font-medium text-brand-primary">
            Support
          </Link>{" "}
          section of your account.
        </p>
        <p className="text-xs text-foreground/50">
          SureCash Digital Technologies Ltd{companyRcNumber ? ` · RC ${companyRcNumber}` : ""}
          <br />
          {companyOfficeAddress}
        </p>
      </LegalSection>
    </LegalPage>
  );
}
